wandb_version: 1

source:
  desc: null
  value: YouTube Video
data:
  desc: null
  value: TEMP
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1703496645.613709
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 53
      - 55
      - 105
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.16.1
      6: 4.36.2
      8:
      - 3
      - 5
      13: windows-amd64
